language: java
jdk:
 - oraclejdk8
services:
 - postgresql
before_script:
 - psql -c 'create database users;' -U postgres
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: monopoly-in-map