spring:
  datasource:
    url: jdbc:postgresql://localhost/users
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org:
      springframework: info
server:
  port: 8080

security:
  oauth2:
    client:
      clientId: 6421813
      clientSecret: MQkAtw8xDuaRYoEjTzAA
      accessTokenUri: https://oauth.vk.com/access_token
      userAuthorizationUri: https://oauth.vk.com/authorize
      tokenName: code
      authenticationScheme: query
      clientAuthenticationScheme: form
      grant-type: authorization_code
    resource:
      userInfoUri: https://api.vk.com/method/users.get