spring:
  datasource:
    url: jdbc:postgresql://localhost/users
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org:
      springframework: info
server:
  port: 8080

security:
  oauth2:
    client:
      clientId: 169804934687-gt2t00vhrepaubn87vtjqdor8imio6pl.apps.googleusercontent.com
      clientSecret: p4QjvzUFKvouet5LkX7JwZ1o
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: query
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
