spring:
  datasource:
    url: jdbc:postgresql://localhost/users
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org:
      springframework: info
server:
  port: 8080

security:
  oauth2:
    client:
       clientId: e7a663e9ac916682020c
       clientSecret: 493e6dc4a0b8ad04db5716f2d4c0d1245c1ac130
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
    resource:
       userInfoUri: https://api.github.com/user
